package com.cms.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * 🎓 LESSON: Entity Class - Country (Master Data)
 * ============================================================================
 * 
 * This is our first JPA Entity. Let's understand each annotation:
 * 
 * @Entity:
 *          - Marks this class as a JPA entity (maps to a database table)
 *          - Hibernate will create/manage a table for this class
 * 
 * @Table:
 *         - Specifies table name and constraints
 *         - Without @Table, table name would default to class name (Country)
 * 
 * @Data (Lombok):
 *       - Automatically generates:
 *       * Getters for all fields
 *       * Setters for all non-final fields
 *       * toString() method
 *       * equals() and hashCode() methods
 *       * A required args constructor
 *       - This saves us from writing ~50 lines of boilerplate code!
 * 
 * @NoArgsConstructor (Lombok):
 *                    - Generates a no-argument constructor
 *                    - JPA requires this to create instances via reflection
 * 
 * @AllArgsConstructor (Lombok):
 *                     - Generates a constructor with all fields as parameters
 *                     - Useful for creating objects in tests
 * 
 *                     ============================================================================
 *                     CONCEPT: Primary Keys
 *                     ============================================================================
 * 
 *                     Every entity needs a primary key to uniquely identify
 *                     rows:
 * 
 * @Id: Marks the primary key field
 * 
 * @GeneratedValue: Specifies how the key should be generated
 *                  - GenerationType.IDENTITY: Database auto-increment (1, 2, 3,
 *                  ...)
 *                  - GenerationType.AUTO: JPA chooses the best strategy
 *                  - GenerationType.SEQUENCE: Uses database sequence (Oracle,
 *                  PostgreSQL)
 *                  - GenerationType.TABLE: Uses a special table to generate IDs
 * 
 *                  We use IDENTITY because MariaDB/MySQL support AUTO_INCREMENT
 *                  well.
 * 
 *                  ============================================================================
 */
@Entity
@Table(name = "country")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Country {

    /**
     * Primary key - auto-generated by database
     * 
     * Type: Long (not long) because:
     * - Can be null (useful before saving to DB)
     * - JPA works better with wrapper types
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Country name (e.g., "Sri Lanka", "India", "USA")
     * 
     * @Column annotation specifies column properties:
     *         - nullable = false: SQL NOT NULL constraint
     *         - length = 100: VARCHAR(100)
     * 
     *         Without @Column, defaults would be:
     *         - Column name: same as field name
     *         - Nullable: true
     *         - Length: 255
     */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Country code (e.g., "LK", "IN", "US")
     * 
     * unique = true: Ensures no duplicate country codes
     * This creates a UNIQUE constraint in the database
     */
    @Column(unique = true, length = 3)
    private String code;

    /**
     * 🎓 WHY NO RELATIONSHIPS HERE?
     * 
     * Country is master data - it doesn't know about cities (one-way relationship).
     * The City entity will have a @ManyToOne relationship to Country.
     * 
     * This is called a "unidirectional" relationship - navigation goes one way
     * only.
     * You can get Country from City, but not Cities from Country (without a query).
     * 
     * If we wanted bidirectional, we'd add:
     * 
     * @OneToMany(mappedBy = "country")
     *                     private List<City> cities;
     * 
     *                     But this would load all cities when loading a country
     *                     (performance issue!),
     *                     so we keep it unidirectional.
     */
}
